"""empty message

Revision ID: 567d9697c4e4
Revises: d74c47bd0172
Create Date: 2025-10-28 13:17:09.212900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567d9697c4e4'
down_revision = 'd74c47bd0172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint("email", 'users', ['email'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
